### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by char-mines** [leizongmin/tcp-tunnel#29]
I am getting the following error how can I fix it?:

`C:\Users\Owner\Downloads\Website\tcp-tunnel\configs>ttserver -c server.conf

  ████████╗ ██████╗██████╗     ████████╗██╗   ██╗███╗   ██╗███╗   ██╗███████╗██╗
  ╚══██╔══╝██╔════╝██╔══██╗    ╚══██╔══╝██║   ██║████╗  ██║████╗  ██║██╔════╝██║
     ██║   ██║     ██████╔╝       ██║   ██║   ██║██╔██╗ ██║██╔██╗ ██║█████╗  ██║
     ██║   ██║     ██╔═══╝        ██║   ██║   ██║██║╚██╗██║██║╚██╗██║██╔══╝  ██║
     ██║   ╚██████╗██║            ██║   ╚██████╔╝██║ ╚████║██║ ╚████║███████╗███████╗
     ╚═╝    ╚═════╝╚═╝            ╚═╝    ╚═════╝ ╚═╝  ╚═══╝╚═╝  ╚═══╝╚══════╝╚══════╝

2021-01-28 15:15:19.72 <info> load config file C:\Users\Owner\Downloads\Website\tcp-tunnel\configs\server.conf
C:\Users\Owner\AppData\Roaming\nvm\v14.0.0\node_modules\tcp-tunnel\bin\server.js:69
const pidFile = path.resolve(os.tmpDir(), `ttserver-port-${config.value.port}.pid`);
                                ^

TypeError: os.tmpDir is not a function
    at Object.<anonymous> (C:\Users\Owner\AppData\Roaming\nvm\v14.0.0\node_modules\tcp-tunnel\bin\server.js:69:33)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

C:\Users\Owner\Downloads\Website\tcp-tunnel\configs>`

**Comment by leizongmin** [comment]
This is because Node v14 or later version has removed `os.tmpDir()` method, it's recommend use `os.tmpdir()` to instead it.
I just published a new version `tcp-tunnel@0.0.5` to fix this problem, you can try it.
